# Runtime Node

# .github/dependabot.yml

# First I set the version to 2
version: 2

updates:
  # 1. updates for 'develop'
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "node"
      - "update"
    
  # 2. updates for 'develop-v1+node24'
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop-v1+node24"
    schedule:
      interval: "daily"
    
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"

    labels:
      - "dependencies"
      - "node"
      - "v1+node24-maintenance"